
version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: hackathonBack
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${MYSQL_PORT_EXTERNAL}:${MYSQL_PORT_INTERNAL}"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
